### ISSUE TITLE
Process 19644 has exited with status 3735929054

### ISSUE THREAD

**Issue by somethino** [amlweems/sklton-key#1] opened 2020-11-12 00:27 UTC
Don't attach an app, which I don't attach to, they crash

![image](https://user-images.githubusercontent.com/51211894/98879547-e1632e80-2496-11eb-85cf-f91aa82f4580.png)

**Comment by amlweems** [comment] 2020-11-12 02:41
Can you share more details about the binary / source of the program you're trying to attach to?

You'll need to ensure this binary is compiled with debugging enabled and that you can attach to it with delve. For example:

```
go get github.com/go-delve/delve/cmd/dlv
dlv attach <pid>
```

**Comment by amlweems** [comment] 2020-11-16 05:24
Closing for now since I cannot reproduce. Please let me know if you get more details.

**Closed as completed by amlweems** 2020-11-16 05:24 UTC
